apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plausible.fullname" . }}
  labels:
    app: plausible
  {{- include "plausible.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | toString | b64enc }}
  {{- else }}
  SECRET_KEY_BASE: {{ randAlphaNum 90 | toString | b64enc }}
  {{- end }}
  TOTP_VAULT_KEY: {{ .Values.totpVaultKey | toString | b64enc }}
  {{- if .Values.databaseURL }}
  DATABASE_URL: {{ .Values.databaseURL | toString | b64enc }}
  {{- end }}
  {{- if .Values.clickhouseDatabaseURL }}
  CLICKHOUSE_DATABASE_URL: {{ .Values.clickhouseDatabaseURL | toString | b64enc }}
  {{- end }}
  {{- if .Values.databaseCA }}
  DATABASE_CA: {{ .Values.databaseCA | toString | b64enc }}
  {{- end }}
